### ISSUE TITLE
Milestone M3 Summary Document

### ISSUE THREAD

**Issue by albertodvp** [mlabs-haskell/cardanow#60]
# Milestone M3 Summary Document

This document provides a summary of the completion of Milestone M3, including the acceptance criteria and evidence of milestone completion as required.

More details can be found here:
[Project Catalyst Milestone](https://milestones.projectcatalyst.io/projects/1000117/milestones/3)

## Details on Acceptance Criteria Fulfillment

1. **Kupo database snapshots are automatically taken at least once per epoch for each public network (mainnet, preprod, and preview):**
2. **The latest two snapshots for each network are retained, at minimum:**
3. **Anyone can access key metadata about the database snapshots programmatically in JSON format (containing download URL and any other relevant information):**
- Snapshots are automatically created by the system for each public network, ensuring they are taken at least once per epoch and are available [here](https://cardanow.staging.mlabs.city/available-snapshots.json)   
   - Metadata for each snapshot, including the download URL and other relevant details, is accessible programmatically in JSON format. This allows users to programmatically retrieve information about the snapshots.

4. **Files downloaded from each URL are valid Kupo database snapshots:**
5. **The restore script successfully restores the downloaded snapshot (allowing Kupo to continue syncing from that point):**
   - A restore script is provided that successfully restores the downloaded snapshot, enabling Kupo to continue syncing from the restored state without issues. The usage of the restore script is shown in the demo video

7. **The portion of the source code related to creating the snapshots, as well as the restore script, are publicly accessible with an open-source licence:**
8. **Any documentation required for utilizing the caching service is made publicly available:**
   - The source code for creating the snapshots and the restore script are available publicly under an open-source license. This promotes transparency and allows the community to contribute to and utilize the code.
   - Comprehensive documentation for utilizing the caching service is made available to the public, ensuring that users can easily understand and use the service in this repository

## Evidence of Milestone Completion

The following evidence supports the completion of Milestone M3:

- [x] **Source code and documentation** are available in [this GitHub Repository](https://github.com/mlabs-haskell/cardanow).
- [x] **Test suite** verifying acceptance criteria (excluding those not applicable to automated testing) is implemented (see below).
- [x] **Video demo** explaining how to utilize the caching service: [YouTube Demo](https://www.youtube.com/watch?v=BJvfv6Mfq-g)
- [x] **Summary document** that links to specific video timestamps, tests, and acceptance criteria, where applicable: [Summary Document](https://github.com/mlabs-haskell/cardanow/issues/60)
- [x] **Social media post** announcing the availability of the caching service: [Twitter Announcement](https://x.com/MLabs10/status/1800475153534792122)

## Video Timestamps

The following sections can be found in the video demo:

- **Intro:** [0:11](https://youtu.be/BJvfv6Mfq-g?si=NKqRMPCeQWx4_kRj&t=11)
- **Cardanow Overview:** [0:35](https://youtu.be/BJvfv6Mfq-g?si=fCsFbizj7Fattq91&t=35)
- **Kupo Restore Overview:** [1:35](https://youtu.be/BJvfv6Mfq-g?si=Mg7ma0C7CAYC8Ts1&t=95)
- **Restore Script Example:** [3:57](https://youtu.be/BJvfv6Mfq-g?si=aHj3yOfr5SF--lIY&t=237)

## Testing

Tests run automatically in CI when the Nix flake checks are evaluated. The infrastructure code is tested "by construction" as Nix would refuse to evaluate invalid configurations. Application logic tests can be found [here](https://github.com/mlabs-haskell/cardanow/tree/master/cardanow-ts/test)

**Comment by albertodvp** [comment]
This was approved by Catalyst Team
