### ISSUE TITLE
Analyze resource usage and determine what hardware is required going forward

### ISSUE THREAD

**Issue by nrutledge** [mlabs-haskell/cardanow#92]
Goal is to determine what hardware is required going forward in order to avoid further downtime. Do we simply replace the disks? Do we order a beefier server?

## Todo
- [ ] #94
- [ ] #95
- [ ] Determine IO usage by service
- [ ] Determine what we can easily optimize (if anything)
- [ ] Make decision on any hardware related changes (beefier server, new disks, etc.)

**Comment by albertodvp** [comment]
Here is a list obtainer with:
`sudo find / -type f -exec du -h {} + 2>/dev/null | sort -rh | head -n 30`
to find the biggest files:
```
96G     /var/lib/cardanow/snapshots/mainnet/kupo/mainnet-507-6186/kupo.sqlite3
84G     /var/lib/cardanow/exported-snapshots/mainnet/kupo/kupo-mainnet-504-6136.tgz
66G     /var/lib/cardanow/exported-snapshots/mainnet/cardano-db-sync/cardano-db-sync-mainnet-504-6132.tgz
56G     /var/lib/cardanow/exported-snapshots/mainnet/cardano-db-sync/cardano-db-sync-mainnet-504-6134.tgz
56G     /var/lib/cardanow/exported-snapshots/mainnet/cardano-db-sync/cardano-db-sync-mainnet-503-6118.tgz
3.8G    /var/lib/cardanow/exported-snapshots/preview/kupo/kupo-preview-679-13592.tgz
3.8G    /var/lib/cardanow/exported-snapshots/preview/kupo/kupo-preview-677-13551.tgz
3.8G    /var/lib/cardanow/exported-snapshots/preview/kupo/kupo-preview-675-13512.tgz
3.6G    /var/lib/cardanow/exported-snapshots/preview/cardano-db-sync/cardano-db-sync-preview-677-13551.tgz
3.6G    /var/lib/cardanow/exported-snapshots/preview/cardano-db-sync/cardano-db-sync-preview-675-13512.tgz
3.5G    /var/lib/cardanow/exported-snapshots/preview/cardano-db-sync/cardano-db-sync-preview-679-13592.tgz
2.9G    /var/lib/cardanow/exported-snapshots/preprod/cardano-db-sync/cardano-db-sync-preprod-165-3224.tgz
2.9G    /var/lib/cardanow/exported-snapshots/preprod/cardano-db-sync/cardano-db-sync-preprod-164-3215.tgz
2.9G    /var/lib/cardanow/exported-snapshots/preprod/cardano-db-sync/cardano-db-sync-preprod-164-3207.tgz
2.2G    /var/lib/cardanow/exported-snapshots/preprod/kupo/kupo-preprod-165-3224.tgz
2.2G    /var/lib/cardanow/exported-snapshots/preprod/kupo/kupo-preprod-164-3207.tgz
2.1G    /var/lib/cardanow/exported-snapshots/preprod/kupo/kupo-preprod-164-3215.tgz
1.9G    /var/lib/cardanow/snapshots/mainnet/cardano-node/mainnet-507-6186/db/ledger/133636451
1.9G    /var/lib/cardanow/snapshots/mainnet/cardano-node/mainnet-507-6186/db/ledger/133632460
1.7G    /var/lib/cardanow/snapshots/mainnet/cardano-db-sync/mainnet-507-6186/99100793-566327d186-426.lstate
1.7G    /var/lib/cardanow/snapshots/mainnet/cardano-db-sync/mainnet-507-6186/98668786-bdd5cc7013-425.lstate
1.7G    /var/lib/cardanow/snapshots/mainnet/cardano-db-sync/mainnet-507-6186/98236789-9adf5a0888-424.lstate
1.7G    /var/lib/cardanow/snapshots/mainnet/cardano-db-sync/mainnet-507-6186/97804785-d5f76aa25b-423.lstate
1.7G    /var/lib/cardanow/snapshots/mainnet/cardano-db-sync/mainnet-507-6186/97372797-5ef29a8986-422.lstate
1.7G    /var/lib/cardanow/snapshots/mainnet/cardano-db-sync/mainnet-507-6186/96940792-0f49e27f6b-421.lstate
1.7G    /var/lib/cardanow/snapshots/mainnet/cardano-db-sync/mainnet-507-6186/96508787-e89215f9ce-420.lstate
746M    /var/lib/docker/volumes/33ca5795390140459ef0c6fa8ffe8e82889405bd989ef6fde216290422a201b8/_data/base/16384/16928.2
741M    /var/lib/docker/volumes/2cc0671b82ae91936036ccfa132618140b35a7742d52ff03acae7fa90c0037ef/_data/base/16384/16928.2
698M    /var/lib/docker/volumes/33ca5795390140459ef0c6fa8ffe8e82889405bd989ef6fde216290422a201b8/_data/base/16384/16609.1
698M    /var/lib/docker/volumes/2cc0671b82ae91936036ccfa132618140b35a7742d52ff03acae7fa90c0037ef/_data/base/16384/16609.1
```
